provider:
  name: nutanix

data_sources:
  app_group:
    read:
      path: /apps/nutanix.eda.nokia.com
      method: GET

  nutanix_eda_managed_bridge_domain:
    read:
      path: /apps/nutanix.eda.nokia.com/v2/namespaces/{namespace}/nutanixedamanagedbridgedomains/{name}
      method: GET

  nutanix_eda_managed_bridge_domain_list:
    read:
      path: /apps/nutanix.eda.nokia.com/v2/namespaces/{namespace}/nutanixedamanagedbridgedomains
      method: GET

  nutanix_plugin_instance:
    read:
      path: /apps/nutanix.eda.nokia.com/v2/nutanixplugininstances/{name}
      method: GET

  nutanix_plugin_instance_list:
    read:
      path: /apps/nutanix.eda.nokia.com/v2/nutanixplugininstances
      method: GET

  resource_list:
    read:
      path: /apps/nutanix.eda.nokia.com/v2
      method: GET

resources:
  nutanix_eda_managed_bridge_domain:
    create:
      path: /apps/nutanix.eda.nokia.com/v2/namespaces/{namespace}/nutanixedamanagedbridgedomains
      method: POST
    read:
      path: /apps/nutanix.eda.nokia.com/v2/namespaces/{namespace}/nutanixedamanagedbridgedomains/{name}
      method: GET
    update:
      path: /apps/nutanix.eda.nokia.com/v2/namespaces/{namespace}/nutanixedamanagedbridgedomains/{name}
      method: PUT
    delete:
      path: /apps/nutanix.eda.nokia.com/v2/namespaces/{namespace}/nutanixedamanagedbridgedomains/{name}
      method: DELETE

  nutanix_plugin_instance:
    create:
      path: /apps/nutanix.eda.nokia.com/v2/nutanixplugininstances
      method: POST
    read:
      path: /apps/nutanix.eda.nokia.com/v2/nutanixplugininstances/{name}
      method: GET
    update:
      path: /apps/nutanix.eda.nokia.com/v2/nutanixplugininstances/{name}
      method: PUT
    delete:
      path: /apps/nutanix.eda.nokia.com/v2/nutanixplugininstances/{name}
      method: DELETE
